<template>
  <div class="">
    <app-aroundTheRealm :roomID="$route.params.roomID" v-if="routeGSheetID == 'Around-The-Realm'"></app-aroundTheRealm>
    <app-clashAtIkara :roomID="$route.params.roomID" v-if="routeGSheetID == 'Clash-At-Ikara'"></app-clashAtIkara> 
    <app-postWorkParadise :roomID="$route.params.roomID" v-if="routeGSheetID == 'Post-Work-Paradise'"></app-postWorkParadise>
  </div>
</template>

<script>
import AroundTheRealm from './AroundTheRealm.vue'
import ClashAtIkara from './ClashAtIkara.vue'
import PostWorkParadise from './PostWorkParadise.vue';

export default {
  name: 'app-customGameSession',
  components: {
    'app-aroundTheRealm': AroundTheRealm,
    'app-clashAtIkara': ClashAtIkara,
    'app-postWorkParadise': PostWorkParadise,
  },
  props: {
    routeGSheetID: String,
  },
  data: function() {
    return {
      gameMetaData: {
        'Around-The-Realm': {
          'gameTitle': 'Around The Realm',
          'gameBlurb': 'Tell the story of two close companions racing their way around a fantasy world. Nella and Bly wagered that they could travel completely around the realm and return before the summer solstice. However, the lands are full of magic, danger, and adventure – will they make it back in time?',
          'ogImage': 'https://diegeticgames.com/uploads/around-the-realm-square-unfurl.png', 
        },
        'Clash-At-Ikara': {
          'gameTitle': 'Clash at Ikara',
          'gameBlurb': 'Tell the story of a group of heroes who have agreed to protect the defenseless community of Ikara from an immenent bandit raid.',
          'ogImage': 'https://diegeticgames.com/uploads/clash-at-ikara-square.png'
        },
        'Post-Work-Paradise': {
          'gameTitle': 'Post-Work Paradise',
          'gameBlurb': "This game explores what life might be like in a world where work is obsolete. How do people choose to live and spend their time? <br><br> Designed by Randy Lubin of <a target='_blank' href='https://leveragedplay.com'>Leveraged Play</a>. Submitted as part of the <a target='_blank' href='https://postwork.city/'>The Post-Work City</a> open call for visions for a future without work.<br><br>Play involves seeing randomly generated residents of this future city and answering questions about their lives. Character photos are generated by Artifical Intelligence via <a target='_blank' href='https://thispersondoesnotexist.com/'>This Person Does Not Exist</a>."
        }
      }
    };
  },
  metaInfo () {
    return {
      title: this.gameMetaData[this.routeGSheetID].gameTitle,
      meta: [
        {
          property: 'description',
          content: this.gameMetaData[this.routeGSheetID].gameBlurb,
          vmid: 'description'
        },
        {
          property: 'og:title',
          content: this.gameMetaData[this.routeGSheetID].gameTitle,
          vmid: 'og:title'
        },
        {
          property: 'og:description',
          content: this.gameMetaData[this.routeGSheetID].gameBlurb,
          vmid: 'og:description'
        },
        {
          property: 'og:image',
          content: this.gameMetaData[this.routeGSheetID].ogImage,
          vmid: 'og:image'
        },
        {
          property: 'og:url',
          content: location.hostname.toString() + "/#" + this.$route.fullPath,
          vmid: 'og:url'
        },
        {
          property: 'twitter:card',
          content: 'summary',
          vmid: 'twitter:card'
        },
        {
          property: 'og:site_name',
          content: 'Story Synth',
          vmid: 'og:site_name'
        },
        {
          property: 'twitter:image:alt',
          content: this.gameMetaData[this.routeGSheetID].gameTitle + " logo",
          vmid: 'twitter:image:alt'
        }
      ]
    }
  },
  mounted(){
    document.dispatchEvent(new Event("x-app-rendered"))
  },
  methods: {

  }
};
</script>

<style scoped>


</style>