var customGameData = {
  "Around-The-Realm": {
    gameType: "Phases",
    "gameTitle": "Around The Realm",
    "gameBlurb":
      "Tell the story of two close companions racing their way around a fantasy world. Nella and Bly wagered that they could travel completely around the realm and return before the summer solstice.",
    "ogImage":
      "https://diegeticgames.com/uploads/around-the-realm-square-unfurl.png",
    "ogImageSquare":
      "https://diegeticgames.com/uploads/around-the-realm-square-unfurl.png",
    "customOptions": {
      "gameTitle": "Around the Realm",
      "byline": "By Randy Lubin",
      "gameBlurb":
        "<div class='text-left' style='white-space:normal'>\n<h2>Pitch</h2>\nTell the story of two close companions racing their way around a fantasy world.\n<br><br>\nNella and Bly wagered that they could race completely around the realm and return before the summer solstice. However, the lands are full of magic, danger, and adventure – will they make it back in time?\n<br><br>\n<h2>Info</h2>\n<ul>\n  <li>2+ players</li>\n  <li>All ages</li>\n  <li>30 minutes - 2 hours</li>\n  <li>Genre: Fantasy</li>\n  <li>Tone: exciting adventure</li>\n  <li>Activities: light narration, quick worldbuilding</li>\n</ul>\n</div>",
      "coverImage":
        "https://diegeticgames.com/uploads/around-the-realm-cover-narrow.png",
      "style":
        "<link href='https://fonts.googleapis.com/css?family=IM+Fell+English|Montserrat' rel='stylesheet'>\n\n<style>\n\n#app {Font-Family: 'IM Fell English', Serif;}\n\n.card-header-text {\n  font-size: 2.5rem;\n  Font-Family: 'IM Fell English', Serif;\n}\n\n.card {\n  background-image: url(https://diegeticgames.com/uploads/groovepaper.png);\n}\n\n.card-img-bottom {\n  filter: saturate(0.7);\n  object-fit: cover;\n  object-position: top;\n  height: 60px;\n}\n\n.full-page-background {\n  background: rgb(255,255,255);\n  background: linear-gradient(180deg, rgba(30,150,255,1) 0%, rgba(255,255,255,1) 300px, rgba(255,255,255,1) 100%);\n  background-image: url('https://diegeticgames.com/uploads/around-the-realm-background.png');\n  filter: sepia(1) grayscale(0.4) brightness(1);\n}\n\n</style>",
    },
    sheetData: [
      ['-', '-', '-', 'Transit', 'Escapade', 'Resolution', 'Settlement', 'Escapade', 'Resolution'],
      ["option", "gameBlurb", "<div class=\"text-left\" style=\"white-space:normal\">\n<h2>Pitch</h2>\nTell the story of two close companions racing their way around a fantasy world.\n<br><br>\nNella and Bly wagered that they could race completely around the realm and return before the summer solstice. However, the lands are full of magic, danger, and adventure – will they make it back in time?\n<br><br>\n<h2>Info</h2>\n<ul>\n  <li>2+ players</li>\n  <li>All ages</li>\n  <li>30 minutes - 2 hours</li>\n  <li>Genre: Fantasy</li>\n  <li>Tone: exciting adventure</li>\n  <li>Activities: light narration, quick worldbuilding</li>\n</ul>\n</div>", "-", "-", "-", "-", "-", "-"],
      ["option", "wallet", "$ilp.uphold.com/WMbkRBiZFgbx", "", "", "", "", "", ""],
      ["option", "revShare", "0.2", "", "", "", "", "", ""],
      ["option", "coverImage", "https://diegeticgames.com/uploads/around-the-realm-cover-narrow.png", "", "", "", "", "", ""],
      ["option", "cardBackgroundImage", "https://diegeticgames.com/uploads/card-bottom-wave2.png", "", "", "", "", "", ""],
      ["option", "cardBackgroundImageAlign", "bottom", "", "", "", "", "", ""],
      ["option", "ogImageSquare", "https://diegeticgames.com/uploads/around-the-realm-square-unfurl.png"],
      ["option", "style", "<link href=\"https://fonts.googleapis.com/css?family=IM+Fell+English|Montserrat\" rel=\"stylesheet\">\n\n<style>\n\n#app {Font-Family: 'IM Fell English', Serif;}\n\n.card-header-text {\n  font-size: 2.5rem;\n  Font-Family: 'IM Fell English', Serif;\n}\n\n.card {\n  background-image: url(https://diegeticgames.com/uploads/groovepaper.png);\n}\n\n.card-img-bottom {\n  filter: saturate(0.7);\n  object-fit: cover;\n  object-position: top;\n  height: 60px;\n}\n\n.full-page-background {\n  background: rgb(255,255,255);\n  background: linear-gradient(180deg, rgba(30,150,255,1) 0%, rgba(255,255,255,1) 300px, rgba(255,255,255,1) 100%);\n  background-image: url(\"https://diegeticgames.com/uploads/around-the-realm-background.png\");\n  filter: sepia(1) grayscale(0.4) brightness(1);\n}\n\n</style>", " ", "-", "-", "-", "-", "-"],
      ["option", "showPastPrompts", "1,0,0,1,0,0", "-", "-", "-", "-", "-", "-"],
      ["option", "pastPromptHeader", "Itinerary", "", "", "", "", "", ""],
      ["option", "pastPromptPrecursor", "Home\n<br>\n|", "", "", "", "", "", ""],
      ["option", "pastPromptCoda", "Home Again", "", "", "", "", "", ""],
      ["option", "instructionsProgressBar", "show", "", "", "", "", "", ""],
      ["option", "phaseHelpText", "Describe the environment, the mode of travel, the fellow travellers, or local rumors|Describe who instigates, who escalates, and what's at stake|Resolve this tangent and set the characters up to arrive at their next destination|Describe the local sights, sounds, and culture|Describe who instigates, who escalates, and what's at stake|Resolve this tangent and set the characters up to continue their journey", "-", "-", "-", "-", "-", "-"],
      ["0", "Around the Realm\n(in 80 days)\n\n🧳🏰⛰🐉🪂🏜🐪⛵️🏝🧜🏽🌋🧳", "One player should hit NEXT to move onto the next card", "-", "-", "-", "-", "-", "-"],
      ["0", "Get Started", "Take turns reading these cards – whomever reads the card should hit NEXT when they're done.", "-", "-", "-", "-", "-", "-"],
      ["0", "The Pitch", "In this game, you'll tell the story of two characters racing around a fantasy realm and getting in and out of trouble (repeatedly). It will be light in tone and fast paced.", "-", "-", "-", "-", "-", "-"],
      ["0", "The Setting", "This story takes place on the The Whirl - an archipelago of islands in the shape of a circle. The islands contain myriad kingdoms and city states; the sea at the center of The Whirl contains a massive and unending maelstrom, the result of a spell gone wrong in centuries past.", "-", "-", "-", "-", "-", "-"],
      ["0", "The Setting", "The lands of The Whirl are constantly jockeying for wealth and status, often through war and always through commerce, espionage, and magic.", "-", "-", "-", "-", "-", "-"],
      ["0", "The Setting", "For the first time in decades, all the lands of The Whirl are at peace. This means it's finally safe to travel in a complete loop around The Whirl and return back home. This hasn't been done in recent memory.", "-", "-", "-", "-", "-", "-"],
      ["0", "The Characters", "Our story centers on two characters – Nella and Bly – who are attempting to circle The Whirl in record time. They have known each other for ages. We'll jointly control and narrate their adventures.\n\nChoose their relationship:\n– Expert and apprentice\n– Siblings\n– Romantic partners\n– Business partners\n– Childhood friends\n\nThen, choose their pronouns", "-", "-", "-", "-", "-", "-"],
      ["0", "The Characters", "Nella and Bly are sharp foils of each other.\n\nFor each of these matched traits, assign one to each character:\n<div class=\"text-center\">\nBook smart OR Street smart\nCourageous OR Cautious\nGregarious OR Shy \n</div>", "-", "-", "-", "-", "-", "-"],
      ["0", "The Characters", "As a group, name something that Nella and Bly like and dislike about their home city.", "", "", "", "", "", ""],
      ["0", "The Characters", "Nella and Bly have boasted that they can travel the entire Whirl and return before the summer solstice. An acquaintance of theirs is skeptical and offers a substantial wager.\n\nChoose what is at stake:\n– An immense amount of wealth\n– Honor and glory\n– A prestigious job\n– A magical artifact\n", "-", "-", "-", "-", "-", "-"],
      ["0", "The Rules", "The story will unfold over a series of vignettes as Nella and Bly navigate The Whirl and try to win the wager. They'll never stay in one place for too long but they could encounter the same travelers and factions in different parts of the realm.", "-", "-", "-", "-", "-", "-"],
      ["0", "The Rules", "Play alternates between Travel rounds and Settlement rounds.\n\nIn a round, the sequence of actions are:\n1) A player describes the new mode of Travel or new Settlement, embellishing what is on the prompt\n2) The next player then draws an Escapade prompt that describes how the characters get into trouble or encounter an opportunity\n3) The next player resolves the situation and gets the characters back on track (arriving at or leaving from a settlement)\n\nThen a player draws a new Travel or Settlement card and the next round begins – make sure to alternate who is drawing the Travel and Settlement cards.", "-", "-", "-", "-", "-", "-"],
      ["0", "The Rules", "When it's your turn, feel free to embellish on the prompt as much as you like. You can ask other players for suggestions, and they can ask follow-up questions, but control of the narrative is ultimately up to you.\n\nFor Settlements: mention the sights, sounds, and smells. For Travel: describe the scenery and the fellow travellers.\n\nEscapades are usually caused by one character or both, perhaps due to their traits. Keep the tone light.\n\nThe characters might get back on track through their own cunning or with the help of an ally. Say whether they're better or worse for the ordeal.", "-", "-", "-", "-", "-", "-"],
      ["0", "The Rules", "Continue through this cycle until you're ready to end the game:\n\n1. Travel\n2. Escapade\n3. Resolution\n4. Settlement\n5. Escapade\n6. Resolution\n\nThen, click the ENDING button and answer the final prompts.", "-", "-", "-", "-", "-", "-"],
      ["0", "The Rules", "If you need to pause the game for any reason, especially if you want to discuss, edit, or reverse any content decisions, just click the X-Card button.", "-", "-", "-", "-", "-", "-"],
      ["0", "Let's get this adventure started", "You're ready to start playing!\n\nHit NEXT to begin and then have one player describe the first form of Travel as Nella and Bly make their way around the Whirl.\n\nThen, keep rotating players and answering prompts until you're ready to end the game.", "-", "-", "-", "-", "-", "-"],
      ["1", "-", "-", "A network of magical portals, part of a new experiment by a bright young mage", "Under suspicion from government investigators", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?", "The city of the undead, where teams of skeletons power all infrastructure under the watchful eyes of necromancer-administrators", "A massive siege begins and no one can enter or exit the settlement", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?"],
      ["1", "-", "-", "A caravan of merchants, travelling together for safety as they pass through dangerous territory between destinations", "Targeted by con artists, as smooth as they are devious", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?", "A sunken, submerged city that is protected from the water by an ancient enchantment", "A case of mistaken identity", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?"],
      ["1", "-", "-", "In carriages with an archeological expedition that has been mapping out the region in search of powerful artifacts", "Attacked by thieves, bandits, or pirates", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?", "Magic is omnipresent, though all controlled by the tyrant-mage who runs the city from their wizard's tower", "A magical experiment; a bold foray in the arcane to uncover new truths or create epic works", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?"],
      ["1", "-", "-", "On the backs of dragons who have been domesticated for this purpose", "A encounter with megafauna, up close and personal", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?", "A temporary tent city built by nomads and merchants in the weeks before the summer solstice", "The animals have escaped from the zoo and they are everywhere", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?"],
      ["1", "-", "-", "On foot as the terrain is too treacherous for carriages and horses", "A natural or magical disaster disrupts the journey", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?", "For as far as you can see, the land has been strip-mined – a small community occupies the remains of what was once a great city", "A maze of bureaucracy and an army of pencil pushers", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?"],
      ["1", "-", "-", "By ship through an archipelago of glimmering islands and unpredictable currents", "A mutiny or rebellion by the crew or travelling companions", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?", "An eco-paradise – a thriving city is deeply integrated into the surrounding jungle and local fauna contribute to a continuous symphony", "Revolution spreads throughout the settlement", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?"],
      ["1", "-", "-", "By a flying ship, the last surviving vessel from an ancient fleet\n", "An alluring side trek, off the direct route", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?", "This city is floating high above the surrounding farmland, levitated by some arcane contraption to protect itself from threats", "The leaders of the settlement strongly suggest that Nella and Bly stay, or else...", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?"],
      ["1", "-", "-", "On horseback, with a diplomatic delegation who are hoping to establish formal relations between once rival states", "A physical obstacle blocks the way forward", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?", "A city of clockwork automatons bustling through the streets; oddly few humans though", "Love at first sight", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?"],
      ["1", "-", "-", "Underground, through an endless and labyrinthine cave network ", "A malfunction, breakdown, or problem with the mode of transit", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?", "The city is built into a mountain, with dense networks of tunnels and vaulted chambers", "Rumors of a lost tome of great wisdom", "How do the characters resolve the escapade and get back on track?\n\nDid they gain or lose anything or anyone in the process?"],
      ["2", "The Road Home", "Nella and Bly are almost back home. Answer the following as a group:\n–Do they expect to make it back by the summer solstice?\n–How do the feel about their journey being so close to an end?", "-", "-", "-", "-", "-", "-"],
      ["2", "Home Again", "Nella and Bly are greeted by the familiar sights and sounds of their hometown.\n\nAs a group, answer the following questions about the characters:\n– Did they win the wager?\n– What are their plans for the future?\n– How has their relationship with each other changed?", "-", "-", "-", "-", "-", "-"],
      ["2", "The End", "<div class=\"text-center\">\nThanks for playing!\n\nYou can share <a target=\"_blank\" href=\"https://storysynth.org/#/Phases/10dXt64oWecErQ0ooCXa1D9dZXfP4WPO7ujwoFsAUN6k\">this link</a> to create new sessions of Around the Realm. Tell your friends!\n</div>", "-", "-", "-", "-", "-", "-"],
      ["2", "Credits", "Game by Randy Lubin, <a target=\"_blank\" href=\"https://diegeticgames.com\">Diegetic Games</a>\n\nArt includes maps generated through <a target=\"_blank\" href=\"https://azgaar.github.io/Fantasy-Map-Generator/\">Azgaar's Fantasy Map Generator</a>\n\nWaves on the bottom of the cards <a target=\"_blank\" href=\"http://www.freepik.com\">Designed by Freepik</a>", "-", "-", "-", "-", "-", "-"],
      ["2", "Under the Hood", "This game is powered by this <a target=”_blank” href=\"https://docs.google.com/spreadsheets/d/10dXt64oWecErQ0ooCXa1D9dZXfP4WPO7ujwoFsAUN6k/edit?usp=sharing\">Google Sheet</a>. Check out <a target=\"_blank\" href=\"https://storysynth.org\">Story Synth</a> to make your own spreadsheet driven games for free!", "-", "-", "-", "-", "-", "-"]
    ]
  },
  "Post-Work-Paradise": {
    gameType: "SlotMachine",
    "gameTitle": "Post-Work Paradise",
    "gameBlurb":
      "This game explores what life might be like in a world where work is obsolete. How do people choose to live and spend their time?",
    "ogImage": "https://storysynth.org/img/story-synth-square-logo.gif",
    sheetData: [
      ["option", "gameTitle", "Post-Work Paradise", "", "", "", "", "", "", ""],
      ["option", "byline", "By Randy Lubin", "", "", "", "", "", "", ""],
      ["option", "gameBlurb", "This game explores what life might be like in a world where work is obsolete. How do people choose to live and spend their time?\n\nDesigned by Randy Lubin of <a target=\"_blank\" href=\"https://leveragedplay.com\">Leveraged Play</a>. Submitted as part of the <a target=\"_blank\" href=\"https://postwork.city/\">The Post-Work City</a> open call for visions for a future without work.\n\nPlay involves seeing randomly generated residents of this future city and answering questions about their lives. Character photos are generated by Artifical Intelligence via <a target=\"_blank\" href=\"https://thispersondoesnotexist.com/\">This Person Does Not Exist</a>.", "", "", "", "", "", "", ""],
      ["option", "style", "<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n<link href=\"https://fonts.googleapis.com/css2?family=Orbitron&family=Roboto&display=swap\" rel=\"stylesheet\">\n\n<style>\n\n.full-page-background {\n background: #e65c00;  /* fallback for old browsers */\n background: -webkit-linear-gradient(to right, #F9D423, #e65c00);  /* Chrome 10-25, Safari 5.1-6 */\n background: linear-gradient(to right, #F9D423, #e65c00); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */\n}\n\n#app {\n font-family: 'Roboto',Arial,sans-serif;\n}\n\nh1, h2 { font-family: 'Orbitron', sans-serif;}\n\n</style>", "", "", "", "", "", "", ""],
      ["option", "instructionsProgressBar", "TRUE", "", "", "", "", "", "", ""],
      ["0", "Welcome to the Future", "This game explores what life might be like in a futuristic city where work is obsolete. Take turns telling the stories of how people live and spend their time.", "-", "-", "-", "-", "-", "-", "-"],
      ["0", "How to Play", "This game will randomly generate a series of people living in a post-work future along with focused questions for you to answer about them.\n\nYou can share the session URL with others and they will see the same prompt at the same time, though the generated character image might be different.", "-", "-", "-", "-", "-", "-", "-"],
      ["0", "On Your Turn", "Take turns reading about the generated people and then answering the questions at the bottom of their cards.\n\nYour answers can be as elaborate as you want. The other players can ask you follow up questions.", "-", "-", "-", "-", "-", "-", "-"],
      ["0", "Ending the Game", "You can stop play at any time. If you run out of cards, you can hit 'Re-shuffle' to start from the beginning with freshly regenerated characters.", "-", "-", "-", "-", "-", "-", "-"],
      ["0", "About the X-Card", "If you need to pause the game for any reason, especially if you want to discuss, edit, or reverse any content decisions, just click the X-Card button.", "-", "-", "-", "-", "-", "-", "-"],
      ["0", "The Game is about to start", "Hit NEXT to begin", "-", "-", "-", "-", "-", "-", "-"],
      ["1", "-", "-", "<img style=\"max-width:50%\" src=\"https://thispersondoesnotexist.com/image?v=13\">", "<br>", "Passion: Acting", "Personality: Gregarious, Curious", "Housing: Skyscraper condo", "<br>", "<em>What is the highlight of their week?</em>"],
      ["1", "-", "-", "<img style=\"max-width:50%\" src=\"https://thispersondoesnotexist.com/image?v=14\">", "<br>", "Passion: Sports", "Personality: Shy, Caring", "Housing: Townhouse", "<br>", "<em>What is their goal for the year?</em>"],
      ["1", "-", "-", "<img style=\"max-width:50%\" src=\"https://thispersondoesnotexist.com/image?v=15\">", "<br>", "Passion: Music", "Personality: Stubborn, Gregarious", "Housing: Converted warehouse", "<br>", "<em>What do they love about living in this city?</em>"],
      ["1", "-", "-", "<img style=\"max-width:50%\" src=\"https://thispersondoesnotexist.com/image?v=16\">", "<br>", "Passion: Learning", "Personality: Silly, Adventurous", "Housing: Converted office building", "<br>", "<em>What do they hate about living in this city?</em>"],
      ["1", "-", "-", "<img style=\"max-width:50%\" src=\"https://thispersondoesnotexist.com/image?v=17\">", "<br>", "Passion: Community", "Personality: Flexible, Calm", "Housing: Tethered blimp", "<br>", "<em>What is their favorite place to hang out?</em>"],
      ["1", "-", "-", "<img style=\"max-width:50%\" src=\"https://thispersondoesnotexist.com/image?v=18\">", "<br>", "Passion: Volunteering", "Personality: Anxious, Caring", "Housing: Self-driving RV", "<br>", "<em>Why did they move to this city?</em>"],
      ["1", "-", "-", "<img style=\"max-width:50%\" src=\"https://thispersondoesnotexist.com/image?v=19\">", "<br>", "Passion: Visual arts", "Personality: Serious, Optimisitic", "Housing: Dormitory", "<br>", "<em>Who do they live with?</em>"],
      ["1", "-", "-", "<img style=\"max-width:50%\" src=\"https://thispersondoesnotexist.com/image?v=20\">", "<br>", "Passion: Writing", "Personality: Energetic, Practical", "Housing: Underground complex", "<br>", "<em>What obligations do they have?</em>"],
      ["1", "-", "-", "<img style=\"max-width:50%\" src=\"https://thispersondoesnotexist.com/image?v=21\">", "<br>", "Passion: Tinkering", "Personality: Curious, Calm", "Housing: Intentional-living compound", "<br>", "<em>What is their favorite annual event?</em>"],
      ["1", "-", "-", "<img style=\"max-width:50%\" src=\"https://thispersondoesnotexist.com/image?v=22\">", "<br>", "Passion: Curating", "Personality: Spontaneous, Caring", "Housing: Nomadic", "<br>", "<em>Where do they go to be by themselves?</em>"]
    ]
  },
  "Clash-At-Ikara": {
    gameType: "Shuffled",
    "gameTitle": "Clash at Ikara",
    "gameBlurb":
      "Tell the story of a group of heroes who have agreed to protect the defenseless community of Ikara from an imminent bandit raid.",
    "ogImage":
      "https://diegeticgames.com/uploads/clash-at-ikara-square.png",
    "ogImageSquare":
      "https://diegeticgames.com/uploads/clash-at-ikara-square.png",
    sheetData: [
      ["option", "gameTitle", "Clash at Ikara"],
      ["option", "byline", "By Randy Lubin"],
      ["option", "gameBlurb", "<i>By Randy Lubin</i>\n\n<div class=\"text-left\" style=\"white-space:normal\">\n<h2>Pitch</h2>\nPlay as a group of heroes who have agreed to protect the defenseless community of Ikara from an imminent bandit raid. First meet the heroes, then discover Ikara and its inhabitants, and finally see how they fare in a battle against the bandits.\n<br><br>\nInspired by Seven Samurai and For the Queen\n<br><br>\n<h2>Info</h2>\n<ul>\n  <li>2+ players</li>\n  <li>30-60 minutes</li>\n  <li>Genre: Flexible (fantasy or science fiction work well)</li>\n  <li>Tone: tense preparation, heroic sacrifice</li>\n  <li>Activities: tell quick vignettes that build the characters and the world</li>\n</ul>\n</div>"],
      ["option", "coverImage", "https://diegeticgames.com/uploads/clash-at-ikara-cover.png"],
      ["option", "showNextDeckButton", "Next Act"],
      ["extension", "playerTurnOrderHeader", "The Heroes"],
      ["extension", "playerTurnOrderButtonLabel", "Add Hero"],
      ["extension", "playerTurnOrderFirstVisible", "10"],
      ["extension", "playerTurnOrder", "{}"],
      ["option", "hideTitleInSession", "TRUE"],
      ["option", "instructionsProgressBar", "6"],
      ["option", "menuColor", "white"],
      ["option", "style", "<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n<link href=\"https://fonts.googleapis.com/css2?family=Kelly+Slab&display=swap\" rel=\"stylesheet\">\n\n<style>\n\nh1, h2 { font-family: 'Kelly Slab', sans-serif; }\n\n.full-page-background {\n\nbackground: #23074d;  /* fallback for old browsers */\nbackground: -webkit-linear-gradient(to top, #cc5333, #23074d);  /* Chrome 10-25, Safari 5.1-6 */\nbackground: linear-gradient(to top, #cc5333, #23074d); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */\n\n}\n\n.card {\n    background: url(/img/paper.png);\n    border: 0px;\n}\n\n\n</style>"],
      ["0", "Clash at Ikara", "One player should hit NEXT CARD and then players should take turns reading each card aloud.\n<style> .main-card {filter:invert()}</style>"],
      ["0", "The Pitch", "Play as a group of heroes who have agreed to protect the defenseless community of Ikara from an imminent bandit raid.\n\nOne player should hit NEXT CARD and then players should take turns reading each card aloud."],
      ["0", "Safety", "If you need to pause the game for any reason, especially if you want to discuss, edit, or reverse any content decisions, just click the X-Card button."],
      ["0", "The Setting", "The story centers on the defenseless community of Ikara but the broader setting is up to you. As a group, define <b>your</b> Ikara.\n<div class=\"text-left mx-5\">\n– An ancient archive, full of magical tomes\n– An ice mining station, in the asteroid belt\n– A scrapyard, in the slums of a cyberpunk dystopia\n– Or, make up your own setting\n</div>"],
      ["0", "The Story Arc", "This game takes place over four Acts:\n<div class=\"text-left mx-5\">\nAct 1: Meet the heroes\nAct 2: Prepare the defenses\nAct 3: Fight the battle\nAct 4: Explore the aftermath\n</div>\n\nSome of the heroes may die – will their sacrifice be worth it?"],
      ["0", "The Prompts", "In this game, you'll take turns advancing the story by answering prompts. You can always choose to redraw a prompt or to ask another player to answer one in your place.\n\nEach Act will contain its own short instructions which you will read before drawing the prompts.\n\nHit 'Next Card' to begin the story."],
      ["1", "Prelude", "<style> .main-card {filter:invert()}</style>"],
      ["2", "Prelude", "The community of Ikara is frequently harassed by bandits, who threaten violence unless Ikara hands over its scarce resources.\n\nAfter years of suffering, the residents of Ikara have said ENOUGH. They've sought the help of heroes to help ward off the bandit attack and secure the long term safety of the community."],
      ["3", "Act 1", "In which we meet our heroes\n<style> .main-card {filter:invert()}</style>"],
      ["4", "Act 1", "Instructions\n<style> .main-card {filter:invert()}</style>"],
      ["5", "Creating Heroes", "In this act, you will take turns drawing hero cards. On your turn, you will read the hero's description and answer the question. Then, add the hero's archetype (e.g. The Veteran) to the list below (scroll down).\n\nDuring the game, you can refer to each hero by their archetype instead of giving them names."],
      ["6", "Number of Heroes", "Each player will create at least one hero. If there are fewer than five players, each player should create two heroes.\n\nKeep clicking 'Next Card' until you're done creating heroes. Then, click 'Next Act' to proceed to Act 2."],
      ["7", "Hero Backgrounds", "These heroes are not local to Ikara. All have answered the for help and are committed to helping the community.\n\nAs you introduce a hero, mention what relationships they have with the other heroes or with Ikara."],
      ["8", "Act 1", "Scenes\n<style> .main-card {filter:invert()}</style>"],
      ["9", "The Veteran", "You are a jaded veteran who has seen too much combat.\n\nWhy have you chosen to help Ikara?\n\n<small><em>Click Next Act when you have enough heroes (1-2 per player)</em></small>"],
      ["9", "The Untested", "You are an untested youth, fully trained who has never seen combat.\n\nWhy have you chosen to help Ikara?\n\n<small><em>Click Next Act when you have enough heroes (1-2 per player)</em></small>"],
      ["9", "The Charmer", "You lack any combat skills but make up for it with kindness and charm.\n\nWhy have you chosen to help Ikara?\n\n<small><em>Click Next Act when you have enough heroes (1-2 per player)</em></small>"],
      ["9", "The Virtuoso", "You have dedicated your life to martial excellence and your skills are peerless.\n\nWhy have you chosen to help Ikara?\n\n<small><em>Click Next Act when you have enough heroes (1-2 per player)</em></small>"],
      ["9", "The Strategist", "You are a genius when it comes to strategy, tactics, and traps.\n\nWhy have you chosen to help Ikara?\n\n<small><em>Click Next Act when you have enough heroes (1-2 per player)</em></small>"],
      ["9", "The Tinkerer", "You are unparalleled at tinkering with devices and machinery.\n\nWhy have you chosen to help Ikara?\n\n<small><em>Click Next Act when you have enough heroes (1-2 per player)</em></small>"],
      ["9", "The Sage", "Everyone values your wisdom and seeks out your advice.\n\nWhy have you chosen to help Ikara?\n\n<small><em>Click Next Act when you have enough heroes (1-2 per player)</em></small>"],
      ["9", "The Tagalong", "The other heroes did not want you to join them but you came along anyway.\n\nWhy have you chosen to help Ikara?\n\n<small><em>Click Next Act when you have enough heroes (1-2 per player)</em></small>"],
      ["9", "The Returned", "You were born in Ikara but you swore that you'd never return.\n\nWhy have you chosen to come back and help?\n\n<small><em>Click Next Act when you have enough heroes (1-2 per player)</em></small>"],
      ["10", "Act 2", "In which the heroes help Ikara prepare for the bandit attack\n<style> .main-card {filter:invert()}</style>"],
      ["11", "Act 2", "Instructions\n<style> .main-card {filter:invert()}</style>"],
      ["12", "Instructions", "On your turn answer the prompt for the selected hero in the hero tracker.\n\nIf you don't want to answer a prompt, you can ask another player to answer it for their hero or you can choose to draw a different prompt.\n\nClicking on a hero in the tracker will set them to be the active hero."],
      ["13", "Instructions", "You can respond to the prompt however you wish, though a short answer is always okay.\n\nOther players are welcome to ask follow-up questions and clarifications.\n\nWhen you're done exploring the heroes and Ikara, advance to Act 3 for the battle with the Bandits. For a 30 minute game, answer 2 cards per hero."],
      ["14", "Act 2", "Scenes\n<style> .main-card {filter:invert()}</style>"],
      ["15", "The Preparations", "Amid all the preparations you find time to unwind.\n\nWhat is the best way to relax in Ikara?"],
      ["15", "The Preparations", "You skirmish with the bandit scouts and get the better of them.\n\nWhat do you learn from the encounter?"],
      ["15", "The Preparations", "Wherever you look, Ikara bears the scars of past bandit raids.\n\nWhat scars are most notable?"],
      ["15", "The Preparations", "The layout of Ikara has a natural weakness that makes it hard to defend.\n\nWhat is it and how do you attempt to strengthen it?"],
      ["15", "The Preparations", "The layout of Ikara has a natural strong point that will help you during the attack.\n\nWhat is it and how will you take advantage of it?"],
      ["15", "The Preparations", "You set up clever traps for when the bandits attack.\n\nWhat are they?"],
      ["15", "The Preparations", "You improvise weapons out of local resources.\n\nWhat are they?"],
      ["15", "The Preparations", "You hold drills with the locals who will help you during the battle.\n\nWhat tactics do you teach them?"],
      ["15", "The Preparations", "You build defensive fortifications that will help you when the bandits attack.\n\nWhat are they?"],
      ["15", "The Preparations", "You scout ahead and learn something about the bandits that will help you in battle.\n\nWhat is it?"],
      ["15", "The Preparations", "You discover valuable weapons hidden in Ikara.\n\nWhat are they and how do you plan to use them?"],
      ["15", "The Preparations", "In order to maximize your chance of success, part of Ikara must be risked or sacrificed.\n\nWhat is the sacrifice and how do the locals react?"],
      ["15", "The Preparations", "One of the locals does not trust the heroes and wants them gone.\n\nWhat is their reason and how do you change their mind?"],
      ["15", "The Preparations", "A younger local wants to fight alongside you but their family wants them to hide and stay safe.\n\nHow do you handle the situation?"],
      ["15", "The Preparations", "One of the locals is falling in love with you.\n\nHow do you feel about them? Do you act on those feelings?"],
      ["15", "The Preparations", "One of the locals is convinced that you are doomed to failure and they are trying to convince the others that surrender is the only option.\n\nHow do you handle the situation?"],
      ["15", "The Preparations", "A community elder welcomes the heroes into their home.\n\nWhat is the traditional method of welcoming guests in Ikara?"],
      ["15", "The Preparations", "A local makes an impassioned case for why you should settle in Ikara after the battle.\n\nWhat do they say and do you seriously consider it?"],
      ["16", "Act 3", "In which the bandits attack and a terrible price is paid\n<style> .main-card {filter:invert()}</style>"],
      ["17", "Act 3", "Instructions\n<style> .main-card {filter:invert()}</style>"],
      ["18", "Instructions", "On your turn read the prompt and answer the question.\n\nSome of the prompts give you the option to sacrifice yourself to prevent a bad outcome; if you choose to do so, describe your hero going out in a blaze of glory. If you choose not to make the sacrifice, describe the cost of not intervening and mention different contribution you make to the battle.\n\nDepending on the tone of your game, you may want to have the sacrifice be a grevious injury instead of death."],
      ["19", "Instructions", "Once every hero has answered a prompt, you may end the battle and move to Act 4: The Aftermath.\n\nIf you want to extend the battle, you may continue to draw Act 3 prompts until you're ready to end the act."],
      ["20", "Act 3", "Scenes\n<style> .main-card {filter:invert()}</style>"],
      ["21", "The Battle", "A bandit is poised to kill a beloved member of Ikara.\n\nDo you sacrifice yourself to save them?"],
      ["21", "The Battle", "The bandits are about to destroy a massive portion of Ikara.\n\nDo you sacrifice yourself to save it?"],
      ["21", "The Battle", "The bandits are about to wipe out a squad of locals.\n\nDo you sacrifice yourself to save them?"],
      ["21", "The Battle", "You see an opportunity to the bandits' prisoners at the cost of your own life.\n\nDo you sacrifice yourself to save them?"],
      ["21", "The Battle", "You save a fellow hero from certain death.\n\nWho was it and how did you save them?"],
      ["21", "The Battle", "You strike recklessly at the Bandits and come out ahead.\n\nWhat happened?"],
      ["21", "The Battle", "You catch some of the bandits with a pre-laid trap.\n\nWhat was it?"],
      ["21", "The Battle", "You take out the bandit leader, dealing a heavy blow to their morale.\n\nHow did you do it?"],
      ["21", "The Battle", "You undermine a key part of the Bandit assault.\n\nWhat is it and how do you do it?"],
      ["22", "Act 4", "In which we learn the fate of Ikara and the Heroes\n<style> .main-card {filter:invert()}</style>"],
      ["23", "The Fate of Ikara", "Did Ikara win the battle? Decide now, as a group."],
      ["24", "The Fate of the Heroes", "Take turns creating epilogues for your characters.\n\nIf your character died in battle, add some details about the future of Ikara and its residents.\n\nOnce every hero has gone, the game is over."],
      ["25", "The End", "<style> .main-card {filter:invert()}</style>"],
      ["26", "Credits", "Designed by Randy Lubin, Diegetic Games\n\nInspired by Seven Samurai and <a href=\"https://forthequeengame.com/\">For The Queen</a>\n\nPowered by <a href=\"https://docs.google.com/spreadsheets/d/1FIWw_lyefEPF9dc-4C-cBwr9gg3D1QH5vkW89WxGu68/edit?usp=sharing\">this spreadsheet</a> via Story Synth\n<style> .main-card {filter:invert()}</style>"]
    ]
  },
  "Raised-By-Mechs": {
    gameType: "Shuffled",
    sheetID: "1q5LuB6H5F9hxJEZovAS4LJZc6YS8mYs0tOFIcCUp4lA",
    "gameTitle": "Raised By Mechs",
    "gameBlurb":
      "Tell the story of children being raised by a mech on a new planet. Inspired by Raised by Wolves and For the Queen.",
    "ogImage": "https://iili.io/f1zdtn.png",
    "ogImageSquare": "https://iili.io/f1zdtn.png",
  },
  "Aethelreds-Academy": {
    gameType: "Generator",
    "gameTitle": "Æthelred's Academy for Aspiring Heroes",
    "gameBlurb":
      "Tell silly stories about how aspiring heroes go on unlikely quests to earn dubious certifications in adventuring skills. By Greg and Randy Lubin.",
    "ogImage": "https://diegeticgames.com/uploads/aethelreds-logo-square.png",
    "ogImageSquare": "https://diegeticgames.com/uploads/aethelreds-logo-square.png",
    sheetData: [
      ["deck", "instructionText", "instructionBody", "1) Hero: introduce yourself to the committee and say which certification(s) you think you earned", "Certification", "Certification", "Certification", "2) Quest Giver: tell the committe about the goal of the quest", "3) Hero: describe how you approached the quest in an attempt to earn the Certification(s)", "4) Quest Giver: recommend if the Hero should earn the Certification"],
      ["option", "gameTitle", "Æthelred's Academy for Aspiring Heroes", "", "", "", "", "", "", ""],
      ["option", "showGameTitleOnCard", "TRUE", "", "", "", "", "", "", ""],
      ["option", "byline", "By Greg Lubin and Randy Lubin", "", "", "", "", "", "", ""],
      ["option", "coverImage", "https://diegeticgames.com/uploads/aethelreds-logo.png", "", "", "", "", "", "", ""],
      ["option", "gameBlurb", "<h2>By Greg Lubin and Randy Lubin</h2>\n<div class=\"text-left\"><p>Tell silly stories about how aspiring heroes accept unlikely quests to earn dubious certifications in adventuring skills.</p><p>Æthelred's Academy is a non-accredited, for-profit institution. Attendees earn their certifications by going on quests and demonstrating competency in their skills.</p><p>Improvise short stories about these aspiring adventures and see if they succeed!</p>\n<h2 class=\"text-center\">Info</h2><ul class=\"text-left\"><li>2+ players</li><li>All ages</li><li>Play time: from 5 minutes to a two year \"degree\"</li><li>Genre: Fantasy</li><li>Tone: Comedy</li><li>Activity: improvising quest recaps</li></ul>\n<p>Icons via Flaticon designers: Freepik, fjstudio, Eucalyp, and Pixel perfect</p>", "", "", "", "", "", "", ""],
      ["option", "styleTemplate", "fantasy", "", "", "", "", "", "", ""],
      ["option", "upperText", "<div class=\"text-left\">\n<p>Welcome to Æthelred's Academy for Aspiring Heroes, a non-accredited and for-profit institution.</p><p>The proven Æthelred Process&trade; involves sending Heroes on quests where they can demonstrate their mastery of a specific adventuring skill.</p><p>In order to receive a certification for a skill, a Hero must return to Æthelred's to present the details of their quest to our certification-granting panel. Please note that aspiring Heroes will be charged a certification evaluation fee regardless of whether the panel issues a certification. Retrying is permitted, for an additional fee.</p>\n<h2 style=\"width:100%; text-align:center\">Instructions</h2><p>The Æthelred Process&trade; is standardized.  Each round will feature a new aspiring hero trying to get a certification for a skill – choose one player to be the aspiring Hero and another to be the Quest Giver. Any additional players are members of the certification committee.</p>\n<h3 style=\"width:100%; text-align:center\">On Each Round</h3>1) The Hero introduces themselves and which certificate they think they have earned (pick from the options listed).\n2) The Quest Giver introduces what the quest goal was and add some embellishing details about the challenges involved.\n3) The Hero tells the committee how they attempted to accomplish the quest in a manner demonstrating the skill up for certification.\n4) The Quest Giver says how they feel about the outcome of the quest and if they hero should be certified in the skill.\n\n<h3 style=\"width:100%; text-align:center\">Tips</h3><p>Each round should last a few minutes, but feel free to go longer or shorter if that's what the players want.</p><p>If the Hero isn't sure how to proceed, they can always say <i>\"And that's when I turned to the Quest Giver for guidance...\"</i> the Quest Giver player can then help with the storytelling, sharing what they advised the hero.</p><p>If the Quest Giver wants to complicate the Hero's story, they can jump in and say <i>\"You wouldn't believe what happened next...\"</i> and then narrate the next story beat.</p><p>Play as many rounds as you like, with each round featuring a new Hero and Quest Giver. When you are done playing the game, share how you expect Æthelred's Academy will rank in this year's Magical Realms News and World Report's survey of non-accredited, for-profit institutions.</p>\n\n</div>", "", "", "", "", "", "", ""],
      ["option", "generatorRowLayout", "1,3,1,1,1", "", "", "", "", "", "", ""],
      ["option", "style", "<style>\n\n.game-launcher .full-page-background {\n  background-color: rgb(117, 61,0);\n}\n\n.game-launcher .card-body {\n  background-color: white;\n}\n\n.full-page-background {\n    \n}\n\n.generator-row{ }\n.generator-col {\n\n}\n\n.generator-row-1 { }\n.generator-row-2 { }\n.generator-row-3 { }\n\n\n.category-label {\n  background-color: #343a40;\n  color: white;\n}\n\n\n.category-body { }\n\n\n</style>", "", "", "", "", "", "", ""],
      [1,"-","-","<div style=\"font-size: 0.9em\">Say which certification(s) you think you've earned</div>","Pyromancy","Dueling","Acting","Collect ten chickens that have fled the coop","<div style=\"font-size: 0.9em\">What obstacles did you face?\nWhat skills did you use?</div>","<div style=\"font-size: 0.9em\">Were you satisfied with the quest result? Was the Certification skill demonstrated?</div>"  ],
      [1,"-","-","","Necromancy","Animal handling","Meditation","Douse the inferno that's consuming the West End","",""  ],
      [1,"-","-","","Shapeshifting","Archery","Penmanship","Lead a caravan across the wartorn wastes","",""  ],
      [1,"-","-","","Summoning","Sleight of Hand","Ballroom Dance","Scare off the bandits","",""  ],
      [1,"-","-","","Divination","Cartography","Music","Deliver a letter to my aunt","",""  ],
      [1,"-","-","","Illusion","Negotiations","Etiquette","Release the falsely imprisoned","",""  ],
      [1,"-","-","","Artifact Enchanting","History","Tactical Retreat","Alphabetize the great archive","",""  ],
      [1,"-","-","","Telepathy","Stealth","Tax Policy","Help the youth pass their exams","",""  ],
      [1,"-","-","","Divine Favor","Athletics","Arts and Crafts","Wake the great dragon from its hundred year slumber","",""  ],
      [1,"-","-","","Cryptozoology","Herbology","Interior Decorating","Convey an apology to a minor deity","",""  ],
      [1,"-","-","","Teleportation","Medicine","Scrapbooking","Negotiate with the besieging army","",""  ],
      [1,"-","-","","Alchemy","Traps","Riddles","Secure a strategic alliance","",""  ],
      [1,"-","-","","","","","Cook a great feast","",""  ],
      [1,"-","-","","","","","Find the missing treasurer who has a reputation for partying","",""  ],
      [1,"-","-","","","","","Repair the great walls","",""  ],
      [1,"-","-","","","","","Fill in for a missing actor on opening night","",""  ],
      [1,"-","-","","","","","Place first at the town beauty contest","",""  ],
      [1,"-","-","","","","","Catch the Midnight Murderer","",""  ],
      [1,"-","-","","","","","Clean the royal stables","",""  ],
      [1,"-","-","","","","","Train the locals to form a town guard","",""  ],
      [1,"-","-","","","","","Collect the ingredients for a witches stew","",""  ],
      [1,"-","-","","","","","Relight the lighthouse fire","",""  ],
      [1,"-","-","","","","","Lull the great dragon back to sleep","",""  ],
      [1,"-","-","","","","","Collect debts for Aethelred's bursar","",""  ],
      [1,"-","-","","","","","Find 10 new students to enroll in Aethelred's (must pay up front!)","",""  ],
      [1,"-","-","","","","","End the great pestilence","",""  ],
      [1,"-","-","","","","","Catch the biggest fish","",""  ]
    ]
  },
  "Umberdred-Institute": {
    gameType: "Generator",
    sheetID: "1-yrqoN7ZKeLHg0ynob9ZCpUbr64T24IrpX1RuSFUAwY",
    "gameTitle": "The Umberdred Institute for Emerging Evildoers",
    "gameBlurb": "Tell silly stories about how aspiring villains accept unlikely quests to earn dubious certifications in evildoing skills. By Amble Studio.",
    "ogImage": "https://diegeticgames.com/uploads/sized-umberdreds-banner-square.png",
    "ogImageSquare": "https://diegeticgames.com/uploads/sized-umberdreds-banner-square.png",
  },
}

export default customGameData
